# Ref: https://www.tug.org/texlive/quickinstall.html

- name: Update APT cache.
  become: true
  apt:
    update_cache: true
    cache_valid_time: 900

- name: Install texlive.
  become: true
  apt:
    name:
      - texlive
      - texlive-base
      - texlive-binaries
      - texlive-fonts-recommended
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-pictures
      - texlive-plain-generic

- name: Install latexmk (for VS Code extension LaTeX Workshop).
  become: true
  apt:
    name:
      - latexmk
