- name: Get the current user's info.
  user:
    name: "{{lookup('env', 'USER')}}"
  register: curr_user

- name: >
    Install the `containerized-work-env-{{containerized_work_env_name}}`
    starter script.
  template:
    src: containerized-work-env.j2
    dest: "/usr/local/bin/containerized-work-env-{{containerized_work_env_name}}"
    mode: "0o755"
    owner: "{{curr_user.uid}}"
    group: "{{curr_user.group}}"
