- name: Get target user's info.
  user:
    name: "{{target_user}}"
  register: target_user_info

- name: Create the work env folder on the host machine.
  vars:
    work_env_folder: "{{target_user_info.home}}/{{work_env_folder_name}}"
  block:
    - name: Create "{{work_env_folder}}".
      file:
        path: "{{work_env_folder}}"
        state: directory
        owner: "{{target_user_info.uid}}"
        group: "{{target_user_info.group}}"
        mode: "0o755"

    - name: Create sub-folders inside "{{work_env_folder}}".
      file:
        path: "{{work_env_folder}}/{{item.name}}"
        state: directory
        owner: "{{target_user_info.uid}}"
        group: "{{target_user_info.group}}"
        mode: "{{item.mode}}"
      loop:
        - name: ".aws"
          mode: "0o700"
        - name: ".gpg"
          mode: "0o700"
        - name: ".gnupg"
          mode: "0o700"
        - name: ".ssh"
          mode: "0o700"

    - name: Create the sub-folder "code" inside "{{work_env_folder}}".
      copy:
        src: "{{item.name}}"
        dest: "{{work_env_folder}}"
        owner: "{{target_user_info.uid}}"
        group: "{{target_user_info.group}}"
        mode: "{{item.mode}}"
      loop:
        - name: code
          mode: "0o755"
        - name: upstreams
          mode: "0o755"
