# -*- mode: yaml; tab-width: 8; indent-tabs-mode: nil; -*-

vscode_extensions:
  - alefragnani.Bookmarks
  - EditorConfig.EditorConfig
  - marcostazi.VS-code-vagrantfile
  - mauve.terraform
  - ms-azuretools.vscode-docker
  - ms-python.python
  - ms-vscode.cpptools
  - nobuhito.printcode
  - Stephanvs.dot
  - vscoss.vscode-ansible
  - wholroyd.jinja

# vim: set expandtab shiftwidth=2:
