ARG BASE_IMAGE=ubuntu:22.04
FROM $BASE_IMAGE

# NOTE: As of 2024-03-01, we still use `apt-get` because `apt` would
# report the warning of "apt does not have a stable CLI interface. Use
# with caution in scripts."
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install \
    software-properties-common \
    sudo
