ARG BASE_IMAGE=ubuntu:22.04
FROM $BASE_IMAGE

ARG USER_NAME=ywen
ARG USER_ID=1000
ARG GROUP_ID=1000
ARG HOST_GPG_SIGNING_SUBKEY_FILE_NAME="sub_signing.key"
ARG HOST_SSH_PRIVATE_KEY_FILE_NAME="id_rsa"
ARG LOCALE="en_US.UTF-8"
ARG LANGUAGE="en_US"
ARG GIT_USER_EMAIL
ARG GIT_USER_NAME
ARG TZ=Etc/UTC

# The name of this containerized work environment (e.g., 'personal').
ARG WORK_ENV_NAME

RUN groupadd -g ${GROUP_ID} ${USER_NAME} && \
    useradd -r --create-home -u ${USER_ID} -g ${USER_NAME} ${USER_NAME}

# NOTE: As of 2020-06-01, we still use `apt-get` because `apt` would
# report the warning of "apt does not have a stable CLI interface. Use
# with caution in scripts."
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install \
    software-properties-common \
    sudo

RUN adduser ${USER_NAME} sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Switch to the non-root user.
USER ${USER_NAME}

WORKDIR /home/${USER_NAME}/code
