# -*- mode: yaml; tab-width: 8; indent-tabs-mode: nil; -*-

- name: Download and install the Debian package.
  become: yes
  apt:
    deb: "https://dl.google.com/linux/direct/{{ package_name }}"

# vim: set expandtab shiftwidth=2:
