- name: Install sox so we can play a sound.
  apt:
    name:
      - sox
    state: latest

- name: Verify sox is installed successfully.
  command:
    argv:
      - play
      - --version

- name: Get the info of the user {{target_user}}.
  user:
    name: "{{target_user}}"
  register: target_user_info

- name: Create the "sounds" folder for the user {{target_user}}.
  file:
    path: "{{target_user_info.home}}/sounds"
    state: directory
    owner: "{{target_user_info.uid}}"
    group: "{{target_user_info.group}}"
    mode: "0o755"

# Source of the files: https://mixkit.co/free-sound-effects/notification/
# TODO(ywen): I need to double check if there is any license issue with using
# the sounds this way.
- name: Install the notification sounds.
  include_tasks: install-sound.yml
  loop:
    - mixkit-doorbell-single-press-333.wav.txz
    - mixkit-happy-bells-notification-937.wav.txz
    - mixkit-wrong-answer-fail-notification-946.wav.txz
