# -*- mode: yaml; tab-width: 8; indent-tabs-mode: nil; -*-

all:
  # Variables that apply to all hosts.
  vars:
    # SSH login name.
    ansible_user: ywen

    git_user_full_name: "Yaobin Wen"
    git_user_email: "robin.wyb@gmail.com"

  hosts:
    target-name:
      ansible_host: 127.0.0.1

# vim: set expandtab shiftwidth=2 filetype=yaml:
