- name: Get current user's info.
  user:
    name: "{{lookup('env', 'USER')}}"
  register: curr_user_info

- name: Copy bashrc.ssh-agent to the user's home folder.
  copy:
    src: bashrc.ssh-agent
    dest: "{{curr_user_info.home}}/.bashrc.ssh-agent"
    owner: "{{curr_user_info.uid}}"
    group: "{{curr_user_info.group}}"
    mode: "0o644"

- name: Update "{{curr_user_info.home}}/.bashrc".
  lineinfile:
    path: "{{curr_user_info.home}}/.bashrc"
    line: "test -f \"$HOME/.bashrc.ssh-agent\" && . \"$HOME/.bashrc.ssh-agent\""
    state: present
