- name: Check if all the needed variables are defined.
  assert:
    that:
      - code_committer_name is defined
      - code_committer_ubuntu_version is defined
      - code_committer_git_user_email is defined
      - code_committer_git_user_name is defined
      - code_committer_host_code_root_dir is defined
      - code_committer_ssh_private_key_file_path is defined
      - code_committer_gpg_signing_subkey_file_path is defined

- name: Build the Docker image.
  block:
  - name: Create a temporary directory for use.
    tempfile:
      prefix: "{{code_committer_name}}-"
      suffix: ".tmp"
      state: directory
    register: tmpdir

  - name: Copy files that are needed to build the image.
    copy:
      src: "{{item.src}}"
      dest: "{{tmpdir.path}}/{{item.dest_fname}}"
      owner: "{{ansible_env.USER}}"
      group: "{{ansible_env.USER}}"
      mode: "{{item.mode}}"
    loop:
      - src: Dockerfile.code-committer
        dest_fname: Dockerfile.code-committer
        mode: "0o755"
      - src: bashrc.ssh-agent
        dest_fname: bashrc.ssh-agent
        mode: "0o755"
      - src: "{{code_committer_ssh_private_key_file_path}}"
        dest_fname: id_rsa
        mode: "0o600"
      - src: "{{code_committer_gpg_signing_subkey_file_path}}"
        dest_fname: sub_signing.key
        mode: "0o600"

  - name: Build the Docker image.
    docker_image:
      name: "{{committer_image_name}}:{{committer_image_tag}}"
      build:
        args:
          UBUNTU_VERSION: "{{code_committer_ubuntu_version}}"
          GIT_USER_EMAIL: "{{code_committer_git_user_email}}"
          GIT_USER_NAME: "{{code_committer_git_user_name}}"
          HOST_SSH_PRIVATE_KEY_FILE_NAME: "id_rsa"
          HOST_GPG_SIGNING_SUBKEY_FILE_NAME: "sub_signing.key"
          COMMITTER_NAME: "{{code_committer_name}}"
          # NOTE(ywen): `ansible_facts.date_time.tz` could be `EDT` that is
          # not in `/usr/share/zoneinfo` because it only has `EST5EDT`.
          # Therefore, we use the value in `/etc/timezone` directly.
          TZ: "{{lookup('file', '/etc/timezone')}}"
        dockerfile: Dockerfile.code-committer
        path: "{{tmpdir.path}}"
        pull: no
      state: present
      source: build
      force_source: yes

  always:
  - name: Remove the temporary directory.
    file:
      path: "{{tmpdir.path}}"
      state: absent
