- name: Check if all the needed variables are defined.
  assert:
    that:
      - code_committer_name is defined
      - code_committer_ssh_private_key_file_path is defined
      - code_committer_ubuntu_version is defined
      - code_committer_git_user_email is defined
      - code_committer_git_user_name is defined
      - code_committer_host_code_root_dir is defined

- name: Build the docker image and start the docker container.
  vars:
    committer_image_name: "code-committer-{{code_committer_name}}"
    committer_image_tag: "ubuntu-{{code_committer_ubuntu_version}}"
    committer_container_name: "code-committer-{{code_committer_name}}"
  block:
  - name: Create a temporary directory for use.
    tempfile:
      prefix: "{{code_committer_name}}-"
      suffix: ".tmp"
      state: directory
    register: tmpdir

  - name: Copy the Dockerfile.
    copy:
      src: Dockerfile.code-committer
      dest: "{{tmpdir.path}}/Dockerfile.code-committer"
      owner: "{{ansible_env.USER}}"
      group: "{{ansible_env.USER}}"
      mode: '0775'

  - name: Copy the SSH private key file.
    copy:
      src: "{{code_committer_ssh_private_key_file_path}}"
      dest: "{{tmpdir.path}}/id_rsa"
      owner: "{{ansible_env.USER}}"
      group: "{{ansible_env.USER}}"
      # NOTE(ywen): We need to give read permission to the file for now because
      # otherwise this file won't be able to be copied to the desired localation
      # within the Dockerfile which uses a different user ID to access it.
      mode: '0644'

  - name: Build the docker image.
    docker_image:
      name: "{{committer_image_name}}:{{committer_image_tag}}"
      build:
        args:
          UBUNTU_VERSION: "{{code_committer_ubuntu_version}}"
          GIT_USER_EMAIL: "{{code_committer_git_user_email}}"
          GIT_USER_NAME: "{{code_committer_git_user_name}}"
          HOST_SSH_PRIVATE_KEY_FILE_NAME: "id_rsa"
          COMMITTER_NAME: "{{code_committer_name}}"
          TZ: "{{ansible_facts.date_time.tz}}"
        dockerfile: Dockerfile.code-committer
        path: "{{tmpdir.path}}"
        pull: no
      source: build

  - name: Create the docker container as the code committer.
    docker_container:
      name: "{{committer_container_name}}"
      image: "{{committer_image_name}}:{{committer_image_tag}}"
      detach: true
      tty: yes
      mounts:
      - type: bind
        read_only: no
        source: "{{code_committer_host_code_root_dir}}"
        target: "/home/ywen/code"

  always:
  - name: Remove the temporary directory.
    file:
      path: "{{tmpdir.path}}"
      state: absent
