- name: Get current user's info.
  user:
    name: "{{lookup('env', 'USER')}}"
  register: curr_user_info

- name: Create .bashrc.cli-prompt in the user's home folder.
  template:
    src: bashrc.cli-prompt.j2
    dest: "{{curr_user_info.home}}/.bashrc.cli-prompt"
    owner: "{{curr_user_info.uid}}"
    group: "{{curr_user_info.group}}"
    mode: "0o644"

- name: Source .bashrc.cli-prompt in "{{curr_user_info.home}}/.bashrc".
  lineinfile:
    path: "{{curr_user_info.home}}/.bashrc"
    line: "test -f \"$HOME/.bashrc.cli-prompt\" && . \"$HOME/.bashrc.cli-prompt\""
    state: present
