- hosts: all
  name: Set up the sandbox VM.

  pre_tasks:
    - name: Verify that Ansible version meets the requirement.
      assert:
        that: "ansible_version.full is version_compare(minimum_version, '>=')"
        msg: Ansible version {{minimum_version}} or later is required.
      vars:
        minimum_version: 2.7.8

  tasks:
    - name: Show welcome message.
      debug:
        msg: Welcome!
