# -*- mode: yaml; tab-width: 8; indent-tabs-mode: nil; -*-

- name: Install Vagrant if not installed yet.
  when: ansible_facts.packages["vagrant"] is not defined
  block:
  - name: Create a temporary directory for use.
    tempfile:
      prefix: "work-env-"
      state: directory
      suffix: ".tmp"
    register: tmpdir

  - name: Download Vagrant debian package.
    get_url:
      checksum: "{{vagrant_checksum}}"
      dest: "{{tmpdir.path}}/{{vagrant_deb_fname}}"
      mode: 0644
      # YAML multi-line string: https://stackoverflow.com/a/21699210/630364
      url: "https://releases.hashicorp.com/vagrant/\
        {{vagrant_version}}/{{vagrant_deb_fname}}"

  - name: Install Vagrant.
    become: yes
    apt:
      deb: "{{tmpdir.path}}/{{vagrant_deb_fname}}"

  always:
    - name: Remove the temporary directory.
      file:
        path: "{{tmpdir.path}}"
        state: absent

# vim: set expandtab shiftwidth=2:
