# -*- mode: yaml; tab-width: 8; indent-tabs-mode: nil; -*-

- name: Determine the dpkg native architecture.
  command: dpkg --print-architecture
  register: dpkg_architecture
  changed_when: false

- name: Create /var/cache.
  become: true
  file:
    path: /var/cache
    state: directory
    owner: "0"
    group: "0"
    mode: "0o755"

- name: Download the armored GPG key for Hashicorp's APT repository.
  become: true
  get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /var/cache/apt.releases.hashicorp.com.gpg
    owner: "0"
    group: "0"
    mode: "0o644"

- name: Dearmor the GPG key for Hashicorp's APT repository.
  become: true
  command:
    argv:
      - gpg
      - --dearmor
      - -o
      - /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - /var/cache/apt.releases.hashicorp.com.gpg

- name: Add the repository for Vagrant.
  become: true
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{release}} main"
    mode: "0o644"
    filename: hashicorp
  vars:
    release: "{{distribution_release_map[ansible_distribution][ansible_distribution_release]|default(ansible_distribution_release)}}"

- name: Update APT cache.
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 900

- name: Install Vagrant.
  become: true
  apt:
    name:
      - vagrant
    state: latest

- name: Check Vagrant can run successfully.
  command:
    argv:
      - vagrant
      - "--version"
  changed_when: false

# vim: set expandtab shiftwidth=2:
