# -*- mode: yaml; tab-width: 8; indent-tabs-mode: nil; -*-

- name: Determine the dpkg native architecture.
  command: dpkg --print-architecture
  register: dpkg_architecture
  changed_when: false

- name: Set up HashiCorp PPA.
  include_role:
    name: hashicorp-ppa

- name: Install Vagrant.
  become: true
  apt:
    name:
      - vagrant
    state: latest

- name: Check Vagrant can run successfully.
  command:
    argv:
      - vagrant
      - "--version"
  changed_when: false

# vim: set expandtab shiftwidth=2:
