# -*- mode: yaml; tab-width: 8; indent-tabs-mode: nil; -*-

- name: Determine the dpkg native architecture.
  command: dpkg --print-architecture
  register: dpkg_architecture
  changed_when: false

- name: Add the apt key for Vagrant.
  become: yes
  apt_key:
    url: "https://apt.releases.hashicorp.com/gpg"
    id: '0xDA418C88A3219F7B'

- name: Add the repository for Vagrant.
  become: yes
  apt_repository:
    repo: "deb [arch={{arch}}] https://apt.releases.hashicorp.com {{release}} main"
    mode: "0o644"
    # The default Ansible filename for this repository is *not* good, because it
    # includes the td-agent major version number (4) and hence causes repository
    # conflicts when upgrades cross a major version.
    filename: hashicorp-vagrant
  vars:
    arch: "{{dpkg_architecture.stdout_lines[0]}}"
    release: "{{distribution_release_map[ansible_distribution][ansible_distribution_release]|default(ansible_distribution_release)}}"

- name: Update APT cache.
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 900

- name: Install Vagrant.
  become: yes
  apt:
    name:
      - vagrant
    state: latest

# vim: set expandtab shiftwidth=2:
