# -*- mode: yaml; tab-width: 8; indent-tabs-mode: nil; -*-

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3

# vim: set expandtab shiftwidth=2:
