- name: Get the info of the unprivileged user {{unprivileged_user_name}}.
  user:
    name: "{{unprivileged_user_name}}"
  register: unprivileged_user_info

- name: Install my bashrc (~/.bashrc.ywen).
  copy:
    src: bashrc.ywen
    dest: "{{unprivileged_user_info.home}}/.bashrc.ywen"
    owner: "{{unprivileged_user_info.uid}}"
    group: "{{unprivileged_user_info.group}}"
    mode: "0o644"

- name: Source ~/.bashrc.ywen from ~/.bashrc
  lineinfile:
    path: "{{unprivileged_user_info.home}}/.bashrc"
    state: present
    line: 'test -f "$HOME/.bashrc.ywen" && . "$HOME/.bashrc.ywen"'
