# -*- mode: yaml; tab-width: 8; indent-tabs-mode: nil; -*-

# https://code.visualstudio.com/docs/setup/linux

- name: Get the package facts.
  package_facts:
    manager: apt

- name: Install Visual Studio Code.
  when: ansible_facts.packages['code'] is not defined
  block:
    - name: Create a temporary directory for use.
      tempfile:
        prefix: "vscode-"
        suffix: ".tmp"
        state: directory
      register: tmpdir

    - name: Download the GPG key.
      get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: "{{tmpdir.path}}/packages.microsoft.asc"
        mode: "0o644"

    - name: Dearmor the GPG key.
      command:
        argv:
          - gpg
          - --output
          - "{{tmpdir.path}}/packages.microsoft.gpg"
          - --dearmor
          - "{{tmpdir.path}}/packages.microsoft.asc"

    - name: Add the key.
      command: >
        install -o root -g root -m 644 {{tmpdir.path}}/packages.microsoft.gpg
        /etc/apt/trusted.gpg.d/

    - name: Add the repository list file.
      copy:
        content: >
          deb
          [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg]
          https://packages.microsoft.com/repos/vscode stable main
        dest: /etc/apt/sources.list.d/vscode.list
        mode: 0644

    - name: Install Visual Studio Code.
      become: yes
      apt:
        name: ["apt-transport-https", "code"]
        update_cache: yes

  always:
    - name: Remove the temporary directory.
      file:
        path: "{{tmpdir.path}}"
        state: absent

- name: Get the installed extensions.
  command: code --list-extensions
  register: installed
  changed_when: False
  become: yes
  become_user: "{{work_env_user_name}}"

- name: Install Visual Studio Code extensions that haven't been installed.
  command: code --install-extension {{item}}
  # I can't quote the line like this '{{vscode_extensions|difference(...)}}'
  # because otherwise the list is turned into its string representation.
  with_items: |
    {{vscode_extensions|difference(installed.stdout.splitlines())}}
  become: yes
  become_user: "{{work_env_user_name}}"

- name: >
    Enlarge file watcher limit to fix the warning "unable to watch for file
    changes in this large workspace".
  sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    state: present
    reload: yes
    sysctl_set: yes

- name: Get the status of the current user settings.
  vars:
    settings_file: "{{ansible_env.HOME}}/.config/Code/User/settings.json"
  stat:
    path: "{{settings_file}}"
  register: sf_stat

- name: Configure Visual Studio Code to my preferences.
  when: sf_stat.stat.exists
  vars:
    settings_file: "{{ansible_env.HOME}}/.config/Code/User/settings.json"
    current_user_settings: "{{lookup('file', settings_file)|from_json}}"

    # NOTE(ywen): When the same key is present, the value from
    # `vscode_preferred_settings` (i.e., `combine`'s argument) takes the
    # precedence, so my preferred settings are always used.
    merged_settings: >
      {{current_user_settings | combine(vscode_preferred_settings)}}
  block:
    - name: Display the current user settings.
      debug:
        var: current_user_settings

    - name: Display my preferred settings.
      debug:
        var: vscode_preferred_settings

    - name: Display the merged settings.
      debug:
        var: merged_settings

    - name: Get the current user info.
      user:
        name: "{{ansible_env.SUDO_USER|default(ansible_env.USER)}}"
      register: curr_user_info

    - name: Display the current user info.
      debug:
        var: curr_user_info

    - name: Write the merged settings back to the file.
      copy:
        content: "{{merged_settings | to_nice_json}}"
        dest: "{{settings_file}}"
        mode: "{{sf_stat.stat.mode | default('0o644')}}"
        owner: "{{sf_stat.stat.pw_name | default(curr_user_info.name)}}"
        group: "{{sf_stat.stat.gr_name | default(curr_user_info.group)}}"
