# -*- mode: yaml; tab-width: 8; indent-tabs-mode: nil; -*-

- name: Install my bashrc (~/.bashrc.ywen).
  copy:
    src: bashrc.ywen
    dest: "{{ansible_env.HOME}}/.bashrc.ywen"

- name: Source ~/.bashrc.ywen from ~/.bashrc
  lineinfile:
    path: "{{ansible_env.HOME}}/.bashrc"
    state: present
    line: 'test -f "$HOME/.bashrc.ywen" && . "$HOME/.bashrc.ywen"'

# vim: set expandtab shiftwidth=2:
