# -*- mode: yaml; tab-width: 8; indent-tabs-mode: nil; -*-

- name: Add git PPA.
  apt_repository:
    repo: ppa:git-core/ppa

- name: Update APT cache.
  apt:
    update_cache: yes
    cache_valid_time: 900

- name: Install git.
  apt:
    name: git
    state: latest

# vim: set expandtab shiftwidth=2:
