- name: Create /usr/local/bin.
  file:
    path: /usr/local/bin
    state: directory
    mode: "0o755"
    owner: root
    group: root

- name: >
    Install the `containerized-work-env-{{containerized_work_env_name}}`
    starter script.
  template:
    src: containerized-work-env.j2
    dest: "/usr/local/bin/containerized-work-env-{{containerized_work_env_name}}"
    mode: "0o755"
    owner: root
    group: root
