- name: Update APT cache.
  apt:
    update_cache: yes
    cache_valid_time: 900

- name: Install BIND9.
  apt:
    name:
      - bind9
      - bind9utils
      - bind9-doc

- name: Set BIND to IPv4 mode.
  lineinfile:
    backup: no
    create: no
    regexp: "^OPTIONS=\"-u bind\"$"
    line: OPTIONS="-u bind -4"
    path: /etc/default/bind9

# {{hostvars[h]["ansible_default_ipv4"]["address"]}} 
# NOTE(ywen): In the 
- name: Configure the Options file.
  when: server_role == "primary"
  template:
    backup: yes
    src: primary/named.conf.options.j2
    dest: /etc/bind/named.conf.options

- name: Restart BIND.
  systemd:
    name: bind9
    state: restarted
