# -*- mode: yaml; tab-width: 8; indent-tabs-mode: nil; -*-

# Reference: https://docs.docker.com/install/linux/docker-ce/ubuntu/

- name: Install packages to allow apt to use a repository over HTTPS.
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: latest

- name: Install Python packages for SNI verification of CA certificate.
  become: yes
  pip:
    name:
      - urllib3
      - pyOpenSSL
      - ndg-httpsclient
      - pyasn1

- name: Add Docker's official GPG key.
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Set up the stable repository.
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    state: present

- name: Install the latest version of Docker CE.
  become: yes
  apt:
    name:
      - docker-ce

- name: Add "{{ansible_user_id}}" to the "docker" group.
  become: yes
  user:
    name: '{{ansible_user_id}}'
    groups: docker
    append: yes

- name: Install docker-compose.
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-{{ansible_system}}-{{ansible_userspace_architecture}}
    dest: /usr/local/bin/docker-compose
    mode: 0755

# vim: set expandtab shiftwidth=2:
