- hosts: all
  name: >
    Provision the target machine with the docker image and the container as
    a code committer (in order to isolate different commit settings, e.g., the
    user name, user email, and credentials).

  vars:
    code_committer_name: "personal"
    code_committer_ubuntu_version: "22.04"
    code_committer_git_user_email: "robin.wyb@gmail.com"
    code_committer_git_user_name: "Yaobin Wen"

    # Must be provided with "-e" on the command line.
    # code_committer_ssh_private_key_file_path

    # Must be provided with "-e" on the command line.
    # code_committer_gpg_signing_subkey_file_path

    # Must be provided with "-e" on the command line.
    # code_committer_host_code_root_dir

  tasks:
    - name: "Create the docker container as the code committer."
      include_role:
        name: code-committer

    - include_role:
        name: code-committer
        tasks_from: unprivileged
