# -*- mode: yaml; tab-width: 8; indent-tabs-mode: nil; -*-

- hosts: all
  name: >
    Provision the target machine, assuming it's installed with Ubuntu Desktop
    14.04, with the software I like to use.
  tasks:
    - name: Get the package facts.
      package_facts:
        manager: apt

    - name: Perform necessary package upgrades.
      include_role:
        name: ubuntu-14-04-upgrades

    - name: Install and configure git.
      include_role:
        name: git

    - name: Install SSH server.
      include_role:
        name: ssh-server

    - name: Install Google Chrome.
      include_role:
        name: google-chrome

    - name: Install Slack Desktop.
      include_role:
        name: slack

    - name: Install helpful tools.
      become: yes
      apt:
        name:
          - meld
          - nautilus-open-terminal
          - vim

    - name: Install VirtualBox.
      include_role:
        name: virtualbox

    - name: Install Visual Studio Code.
      include_role:
        name: vscode

# vim: set expandtab shiftwidth=2:
