# -*- mode: yaml; tab-width: 8; indent-tabs-mode: nil; -*-

- hosts: all
  name: >
    Provision the target machine, assuming it's installed with Ubuntu Desktop
    18.04, with the software I like to use.
  tasks:
    - name: Get the package facts.
      package_facts:
        manager: apt

    - name: Set up the directory for the dynamically determined host facts.
      include_role:
        name: host-facts

    - name: Install helpful tools.
      become: yes
      include_role:
        name: tools

    - name: Install and configure git.
      include_role:
        name: git

    - name: Install SSH server.
      include_role:
        name: ssh-server

    - name: Install Google Chrome.
      include_role:
        name: google-chrome

    - name: Install Slack Desktop.
      include_role:
        name: slack

    - name: Install vagrant.
      include_role:
        name: vagrant

    - name: Install VirtualBox.
      include_role:
        name: virtualbox

    - name: Install Visual Studio Code.
      include_role:
        name: vscode

    - name: Set up system environment.
      include_role:
        name: system-environment

# vim: set expandtab shiftwidth=2:
