- name: Set up a Python package server.
  hosts: all
  pre_tasks:
    - name: Install Python packages.
      become: yes
      apt:
        name:
        - python-jmespath
        - python3-jmespath
        update_cache: true
        cache_valid_time: 900

  roles:
    - role: geerlingguy.java
      java_packages:
        - openjdk-8-jdk
      become: yes

    - role: geerlingguy.apache
      become: yes
      vars:
        apache_create_vhosts: no
        apache_mods_enabled:
          - "proxy.load"
          - "proxy_http.load"
          - "headers.load"
        apache_remove_default_vhost: true

    - role: ansible-thoteam.nexus3-oss
      become: yes
      vars:
        # We want anonymous access for now for sake of simplicity. We set up
        # this for publishing and downloading our own Python packages and we
        # want the users to do that with a simple `pip install` command without
        # bothering with the username and password.
        nexus_anonymous_access: true

        # We want to create PyPI repositories.
        nexus_config_pypi: true

        # We want backup.
        nexus_backup_configure: true
        nexus_backup_rotate: true
        nexus_backup_keep_rotations: 10

        nexus_privileges:
          # TODO(ywen): `all-repos-read` is already the default value. How can
          # we extend the list instead of overriding?
          - name: all-repos-read
            description: 'Read & Browse access to all repos'
            repository: '*'
            actions:
              - read
              - browse
          - name: python-internal-publishing
            description: "Publish internal Python packages."
            # "pypi-internal" is the default repository name for hosted PyPI.
            # Defined in `defaults/main.yml`.
            repository: pypi-internal
            actions:
              - add
              - edit

        nexus_roles:
        - id: developers  # can map to a LDAP group id, also used as a key to update a role
          name: developers
          description: All developers
          privileges:
            - nx-search-read
            - all-repos-read
            - python-internal-publishing
          roles: []

        nexus_local_users:
          - username: ywen # used as key to update
            first_name: Yaobin
            last_name: Wen
            email: robin.wen@guangyuanbj.com
            password: "s3cr3t"
            roles:
              - Developpers # role ID here
