- name: Set up a Python package server.
  hosts: all
  pre_tasks:
    - name: Install Python packages.
      become: yes
      apt:
        name:
        - python-jmespath
        - python3-jmespath
        update_cache: true
        cache_valid_time: 900

  roles:
    - role: geerlingguy.java
      java_packages:
        # Per [1], it looks like Nexus requires Java 8 exactly. Java 11 (once
        # I installed) wouldn't work.
        # [1] https://help.sonatype.com/repomanager3/installation/system-requirements#SystemRequirements-Java
        - openjdk-8-jdk
      become: yes

    - role: geerlingguy.apache
      become: yes
      vars:
        apache_create_vhosts: no
        apache_mods_enabled:
          - "proxy.load"
          - "proxy_http.load"
          - "headers.load"
        apache_remove_default_vhost: true

    - role: ansible-thoteam.nexus3-oss
      become: yes
      vars:
        # We want anonymous access for now for sake of simplicity. We set up
        # this for publishing and downloading our own Python packages and we
        # want the users to do that with a simple `pip install` command without
        # bothering with the username and password.
        nexus_anonymous_access: true

        # We want to create PyPI repositories.
        nexus_config_pypi: true

        # `pypi-internal` is for internal releases. Once a specific version of
        # a package is uploaded to `pypi-internal`, it cannot be overwritten.
        # `pypi-snapshot` is for development testing, primarily to test if a
        # package can be published successfully, so it allows overwritting.
        nexus_repos_pypi_hosted:
        - name: pypi-internal
          version_policy: release
          write_policy: allow_once
        - name: pypi-snapshot
          version_policy: snapshot
          write_policy: allow

        # We want backup.
        nexus_backup_configure: true
        nexus_backup_rotate: true
        nexus_backup_keep_rotations: 10

        nexus_roles:
        - id: developers
          name: developers
          description: All developers
          privileges:
            - "all-repos-read"
            - "nx-repository-view-pypi-*-*"
            - "nx-search-read"
          roles: []

        nexus_local_users:
          # It looks like all of the fields below are mandatory. If any one is
          # missing, a `NullPointerException` would be thrown.
          - username: ywen # used as key to update
            first_name: Yaobin
            last_name: Wen
            email: robin.wyb@gmail.com
            password: "s3cr3t"
            roles:
              - developers # role ID here
