# https://galaxy.ansible.com/docs/using/installing.html#installing-multiple-roles-from-a-file

- src: geerlingguy.apache
  version: 3.1.4

- src: geerlingguy.java
  version: 1.10.0

- src: ansible-thoteam.nexus3-oss
  version: v2.4.14

