# -*- mode: yaml; tab-width: 8; indent-tabs-mode: nil; -*-

- hosts: all
  name: Install `openssh-server` on the target machines.
  vars:
    ansible_become: yes

  tasks:
    - include_role:
        name: ssh
        tasks_from: install-ssh-server

# vim: set expandtab shiftwidth=2:
