# -*- mode: yaml; tab-width: 8; indent-tabs-mode: nil; -*-

- name: Get the number of running VMs.
  command: vboxmanage list runningvms
  register: runningvms
  # NOTE(ywen): If `virtualbox` is not installed, `vboxmanage` won't be found
  # and the command will fail. We ignore the error and let the following block
  # handle it (see its `when` conditions).
  ignore_errors: yes

# Ref: https://www.virtualbox.org/wiki/Linux_Downloads
- name: >
    Install VirtualBox when `virtualbox` is not installed or
    is installed but there is no running VM.
  # NOTE(ywen): The `when` condition consists of two checks:
  # - 1). Whether `virtualbox` is installed (If not installed, `vboxmanage`
  #   won't be found.)
  # - 2). Whether there is any running VM if `virtualbox` is installed.
  when: >
    (
      (runningvms.rc > 0) and
      (runningvms.msg is defined) and
      (runningvms.msg is search("No such file or directory"))
    ) or
    (
      (runningvms.stdout_lines is defined) and
      (runningvms.stdout_lines|length == 0)
    )
  block:
  - name: Install GPG keys for the VirtualBox APT repository.
    become: yes
    apt_key:
      id: '{{item.id}}'
      url: 'https://www.virtualbox.org/download/{{item.fname}}'
    with_items:
      - id: '0xB9F8D658297AF3EFC18D5CDFA2F683C52980AECF'
        fname: 'oracle_vbox_2016.asc'
      - id: '0x7B0FAB3A13B907435925D9C954422A4B98AB5139'
        fname: 'oracle_vbox.asc'

  - name: >-
      Install prerequisites for building VirtualBox kernel modules
      (required on Ubuntu 18.04).
    become: yes
    apt:
      name: [build-essential, dkms]
      install_recommends: no

  - name: Add the VirtualBox APT repository.
    become: yes
    apt_repository:
      repo: >-
        deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian
        {{ansible_distribution_release}} contrib

  - name: Install VirtualBox {{virtualbox_version}}.
    become: yes
    apt:
      name: virtualbox-{{virtualbox_version}}
      state: present
      install_recommends: no

# vim: set expandtab shiftwidth=2:
