# -*- mode: yaml; tab-width: 8; indent-tabs-mode: nil; -*-

vagrant_version: 2.2.4
vagrant_architecture: x86_64
vagrant_checksum: sha256:1ffb66020b580492ebf9189af8a48c48cdb31825be0717d600518a881584fe4a
deb_fname: vagrant_{{vagrant_version}}_{{vagrant_architecture}}.deb

# vim: set expandtab shiftwidth=2:
