- name: Add the HashiCorp APT key.
  apt_key:
    url: "{{hashicorp_ppa_uri}}/gpg"
    keyring: "{{hashicorp_keyring_path}}"

- name: Determine the dpkg native architecture.
  command: dpkg --print-architecture
  register: dpkg_architecture
  changed_when: false

- name: Add the HashiCorp PPA.
  apt_repository:
    repo: "deb [arch={{arch}} signed-by={{hashicorp_keyring_path}}] {{hashicorp_ppa_uri}} {{ansible_distribution_release}} main"
    mode: "0o644"
  vars:
    arch: '{{dpkg_architecture.stdout_lines[0]}}'

- name: Update APT cache.
  apt:
    update_cache: yes
    cache_valid_time: 900
